// @heliobond/contracts-sdk entry point (#624).
//
// `project_registry/` and `investment_vault/` are generated by
// scripts/build_sdk.sh from the release WASMs (`stellar contract bindings
// typescript`); `networks.ts` is generated from deploy/*.json.
export * as ProjectRegistry from "./project_registry/index.js";
export * as InvestmentVault from "./investment_vault/index.js";
export * from "./networks.js";
