#!/usr/bin/env python3
"""Write sdk/src/networks.ts from deploy/<network>.json (#624).

Each deploy file contributes one entry with its contract IDs and the Stellar
network passphrase / default RPC URL. Networks whose contract IDs are still
empty are emitted too (with empty strings) so consumers get a type-stable
object; `requireContractIds()` in the SDK throws a clear error for them.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "sdk" / "src" / "networks.ts"

KNOWN = {
    "testnet": ("Test SDF Network ; September 2015", "https://soroban-testnet.stellar.org"),
    "mainnet": ("Public Global Stellar Network ; September 2015", "https://mainnet.sorobanrpc.com"),
    "futurenet": ("Test SDF Future Network ; October 2022", "https://rpc-futurenet.stellar.org"),
}


def main() -> None:
    entries = []
    for path in sorted((ROOT / "deploy").glob("*.json")):
        data = json.loads(path.read_text())
        name = data.get("network") or path.stem
        passphrase, rpc = KNOWN.get(name, ("", ""))
        entries.append(
            f"  {json.dumps(name)}: {{\n"
            f"    networkPassphrase: {json.dumps(passphrase)},\n"
            f"    rpcUrl: {json.dumps(rpc)},\n"
            f"    projectRegistry: {json.dumps(data.get('project_registry', ''))},\n"
            f"    investmentVault: {json.dumps(data.get('investment_vault', ''))},\n"
            f"  }},"
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/gen_sdk_networks.py from deploy/*.json — do not edit.\n\n"
        "export interface HeliobondNetwork {\n"
        "  networkPassphrase: string;\n"
        "  rpcUrl: string;\n"
        "  projectRegistry: string;\n"
        "  investmentVault: string;\n"
        "}\n\n"
        "export const networks = {\n" + "\n".join(entries) + "\n} as const satisfies Record<string, HeliobondNetwork>;\n\n"
        "export type HeliobondNetworkName = keyof typeof networks;\n\n"
        "/** Return a network's config, throwing if its contracts aren't deployed yet. */\n"
        "export function requireContractIds(name: HeliobondNetworkName): HeliobondNetwork {\n"
        "  const net = networks[name];\n"
        "  if (!net.projectRegistry || !net.investmentVault) {\n"
        "    throw new Error(`Heliobond contracts are not deployed on ${name} yet (deploy/${name}.json is empty).`);\n"
        "  }\n"
        "  return net;\n"
        "}\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} network(s))")


if __name__ == "__main__":
    main()
